# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER aiden

# 挂载目录
VOLUME /home/stringtest
# 创建目录
RUN mkdir -p /home/stringtest
RUN mvn install
# 指定路径
WORKDIR /home/stringtest
# 复制jar文件到路径
COPY ./jar/aiden.lin-1.0-SNAPSHOT.jar /home/stringtest/aiden.lin-1.0-SNAPSHOT.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","aiden.lin-1.0-SNAPSHOT.jar"]